"""Local no-op LLM provider for testing without API calls (v2)."""

import logging

from polymarket_edges.llm.provider import LLMProvider
from polymarket_edges.models import RulesExtractionOutput, ReportFactsPayload

logger = logging.getLogger(__name__)


class LocalProvider(LLMProvider):
    """Local no-op provider that returns placeholder data."""

    @property
    def model_name(self) -> str:
        """Return the model name."""
        return "local-placeholder"

    async def extract_rules(
        self,
        question: str,
        description: str | None,
        rules: str | None,
    ) -> RulesExtractionOutput:
        """Return placeholder structured rules data (v2)."""

        logger.debug(f"LocalProvider: Generating placeholder rules for '{question[:50]}...'")

        # Return neutral placeholder that allows pipeline to continue
        return RulesExtractionOutput(
            resolution_source="Placeholder - no LLM used",
            primary_measurement="Placeholder measurement",
            yes_conditions=["Placeholder yes condition"],
            no_conditions=["Placeholder no condition"],
            key_dates=[],
            edge_cases=[],
            ambiguity_score=0.5,
            unfalsifiable_flag=False,
            dispute_risk_notes=["No LLM analysis performed (local provider)"],
            recommended_evidence_to_monitor=[],
        )

    async def generate_report(
        self,
        facts: ReportFactsPayload,
    ) -> str:
        """Generate placeholder report."""

        logger.debug(f"LocalProvider: Generating placeholder report for {facts.market_title[:50]}...")

        # Build simple report from facts
        report = f"""# {facts.market_title}

## Outcome: {facts.outcome}

### Payout Conditions

*Local provider: No LLM-based analysis available. See structured rules for details.*

### Key Numbers

| Metric | Value |
|--------|-------|
| Best Bid | {facts.current_best_bid if facts.current_best_bid is not None else 'N/A'} |
| Best Ask | {facts.current_best_ask if facts.current_best_ask is not None else 'N/A'} |
| Mid Price | {facts.current_mid if facts.current_mid is not None else 'N/A'} |
| Spread | {facts.current_spread if facts.current_spread is not None else 'N/A'} |

### Execution Analysis

"""

        # Add execution metrics
        if facts.execution_metrics:
            report += "Execution metrics by trade size:\n\n"
            for size, metrics in facts.execution_metrics.items():
                report += f"**{size} USD notional:**\n"
                report += f"- Entry VWAP: {metrics.get('entry_vwap', 'N/A')}\n"
                report += f"- Exit VWAP: {metrics.get('exit_vwap', 'N/A')}\n"
                report += f"- Liquidity Tax: {metrics.get('liquidity_tax', 'N/A')}\n"
                report += f"- Fill Ratio: {metrics.get('fill_ratio', 'N/A')}\n\n"
        else:
            report += "*No execution metrics available.*\n\n"

        report += """### Constraint Signals

"""
        if facts.constraint_violations:
            report += f"Detected {len(facts.constraint_violations)} constraint violation(s).\n\n"
        else:
            report += "No constraint violations detected.\n\n"

        report += """### Regime Characteristics

"""
        if facts.regime_features:
            for key, value in facts.regime_features.items():
                report += f"- {key}: {value}\n"
        else:
            report += "*No regime features available.*\n"

        report += "\n"

        if facts.belief_posterior_mean is not None:
            report += f"**Belief estimate:** {facts.belief_posterior_mean:.4f} ± {facts.belief_posterior_std:.4f}\n\n"

        report += """### Risk Assessment

*Local provider: No LLM-based risk assessment available.*

---

*This is a placeholder report generated by the local provider (no LLM). For detailed analysis, use the OpenAI provider.*
"""

        return report
